apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootstrap-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bootstrap-app
  template:
    metadata:
      labels:
        app: bootstrap-app
    spec:
      containers:
        - name: bootstrap-app
          image: nandhini1694/final-res:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bootstrap-app-service
spec:
  type: LoadBalancer
  selector:
    app: bootstrap-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000