apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-app
  template:
    metadata:
      labels:
        app: rest-app
    spec:
      containers:
        - name: rest-app
          image: nandhini1694/rest-app:latest
          ports:
            - containerPort: 80
