apiVersion: v1
kind: Service
metadata:
  name: rest-app-service
spec:
  type: NodePort
  selector:
    app: rest-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
